-- File: src/TeamSpeak/Database.hs
{-# LANGUAGE OverloadedStrings #-}

-- | Module for handling SQLite database connections and schema.
module TeamSpeak.Database
    ( Connection -- Export the Connection type from sqlite-simple
    , openConnection
    , closeConnection
    , createSessionTableQuery -- Export the query string for potential inspection
    , ensureSchema
    , insertSession -- Export the new insertion function
    , updateSessionDisconnectTime
    , execute           
    , lastInsertRowId  
    ) where

import TeamSpeak.Types (UserSession(..)) -- Import the UserSession type and its fields
import Database.SQLite.Simple
  ( Connection
  , Query
  , open
  , close
  , execute_
  , execute
  , FromRow(..)
  , ToRow(..)
  , field
  , SQLData(..)
  , lastInsertRowId
  )
import Data.Text (Text) -- Import Text if not already needed for Query
import qualified Data.Text as T -- Import T for T.pack   
import Data.Time.Format (formatTime, defaultTimeLocale, parseTimeM) -- Import for time formatting
import Data.Time (UTCTime) -- Import UTCTime
import Data.Time.Format.ISO8601 (iso8601Show) -- Import a function to format UTCTime as ISO 8601 string
import Data.Int (Int64)

-- | Opens a connection to an SQLite database file.
--   The file will be created if it does not exist.
openConnection :: FilePath -> IO Connection
openConnection = open

-- | Closes the given SQLite database connection.
closeConnection :: Connection -> IO ()
closeConnection = close

-- | The SQL query string to create the `user_sessions` table.
--   Uses TEXT for timestamps as recommended for ISO 8601 strings.
createSessionTableQuery :: Query
createSessionTableQuery = 
    "CREATE TABLE IF NOT EXISTS user_sessions ( \
    \    id INTEGER PRIMARY KEY AUTOINCREMENT, \
    \    client_id INTEGER NOT NULL, \
    \    client_name TEXT NOT NULL, \
    \    connect_time TEXT NOT NULL, \
    \    disconnect_time TEXT \
    \);"

-- | Ensures the `user_sessions` table exists in the database.
--   Creates the table if it does not already exist.
ensureSchema :: Connection -> IO ()
ensureSchema conn = execute_ conn createSessionTableQuery

-- | SQL query for inserting a new session.
--   Uses placeholders (?) for values to prevent SQL injection.
insertSessionQuery :: Query
insertSessionQuery =
    "INSERT INTO user_sessions (client_id, client_name, connect_time, disconnect_time) VALUES (?, ?, ?, ?);"

-- | Inserts a 'UserSession' record into the 'user_sessions' table.
--   The 'sessionId' field in the input is typically -1 (placeholder).
--   The actual auto-generated ID from the database is not returned here,
--   but the database will assign one.
insertSession :: Connection -> UserSession -> IO ()
insertSession conn session =
  execute conn
    "INSERT INTO user_sessions (client_id, client_name, connect_time, disconnect_time) VALUES (?, ?, ?, ?)"
    session  -- pass the whole UserSession; relies on ToRow instance

-- | Updates the 'disconnect_time' of a 'UserSession' in the 'user_sessions' table by its ID.
--   The 'disconnect_time' is converted from UTCTime to Text for storage.
updateSessionDisconnectTime :: Connection -> Int64 -> UTCTime -> IO ()
updateSessionDisconnectTime conn sessionId disconnectTime = do
  let disconnectTimeText = T.pack $ show disconnectTime
  execute conn
    "UPDATE user_sessions SET disconnect_time = ? WHERE id = ?"
    (disconnectTimeText, sessionId)

-- | Instance to convert a row from the 'user_sessions' table into a 'UserSession'.
instance FromRow UserSession where
  fromRow = do
    sid   <- field  -- Int
    cid   <- field  -- Int
    name  <- field  -- Text
    connT <- field  -- Text
    discT <- field  -- Maybe Text

    let parseTimeSafe :: Text -> Maybe UTCTime
        parseTimeSafe t = parseTimeM True defaultTimeLocale "%Y-%m-%d %H:%M:%S%Q" (T.unpack t)

    case parseTimeSafe connT of
      Nothing -> error $ "Invalid connect_time: " ++ T.unpack connT
      Just ct -> do
        let dt = discT >>= parseTimeSafe
        return UserSession
          { sessionId = sid
          , sessionClientId = cid
          , sessionClientName = name
          , sessionConnectTime = ct
          , sessionDisconnectTime = dt
          }

-- | Instance to convert a 'UserSession' into fields for insertion/querying.
--   Note: The 'sessionId' (the ID auto-generated by the DB) is not included in INSERT/UPDATE values,
--   but might be included in SELECT results.
instance ToRow UserSession where
  toRow s =
    [ SQLInteger (fromIntegral $ sessionClientId s)
    , SQLText (sessionClientName s)
    , SQLText (T.pack $ show $ sessionConnectTime s)
    , case sessionDisconnectTime s of
        Nothing -> SQLNull
        Just t  -> SQLText (T.pack $ show t)
    ]