-- File: app/Main.hs
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Options.Applicative -- Import optparse-applicative
import qualified Data.Text as T -- Import Text for handling the raw log line
import qualified Data.Text.IO as TIO -- Import for readFile
import Data.Time (getCurrentTime) -- Import for time handling if needed later, though not directly used here for parsing
import Control.Monad (forM_) -- Import forM_ for looping over lines
import Data.Time (getCurrentTime, UTCTime) -- Import UTCTime and getCurrentTime for session times

-- Import types and functions from your library
import TeamSpeak.Types (ConnectionEvent(..), ConnectionEventType(..), Client(..), UserSession(..))
import TeamSpeak.Parser (connectionEventParser) -- Import the main parser
import TeamSpeak.Database (openConnection, closeConnection, ensureSchema, insertSession) -- Import DB functions
import Text.Megaparsec (parse, errorBundlePretty) -- Import for running the parser and error handling
import Text.Megaparsec.Char (newline) -- Import newline if needed for parsing, though not directly here
import Data.Void (Void) -- Import Void for the parser's error type

-- | Data structure to hold parsed command-line options.
data Options = Options
  { optLogFile :: FilePath
  , optDbPath  :: FilePath
  } deriving (Show, Eq)

-- | Parser for command-line options.
optionsParser :: Parser Options
optionsParser = Options
  <$> strOption -- Parse a string option
      ( long "log-file" -- Long option name: --log-file
     <> short 'l'       -- Short option name: -l
     <> metavar "FILEPATH" -- Meta variable name for help text
     <> help "Path to the TeamSpeak server log file" -- Help text
      )
  <*> strOption -- Parse another string option
      ( long "db-path" -- Long option name: --db-path
     <> short 'd'      -- Short option name: -d
     <> metavar "DBPATH" -- Meta variable name for help text
     <> help "Path to the SQLite database file" -- Help text
      )

-- | Main entry point of the executable.
main :: IO ()
main = do
  -- Parse command-line arguments using the defined parser
  opts <- execParser (info (optionsParser <**> helper) -- Combine parser with helper (adds --help)
                      ( fullDesc -- Provide full description
                     <> progDesc "Parse TeamSpeak logs and store session data in an SQLite database" -- Program description
                     <> header "teamspeak-server-logparser-cli - A log parser for TeamSpeak servers" -- Header for help text
                      )
                     )
  -- Print the parsed options for now (as a placeholder)
  putStrLn $ "Log file: " ++ optLogFile opts
  putStrLn $ "Database path: " ++ optDbPath opts
  putStrLn "Placeholder: Actual processing would happen here."

  -- Open database connection
  conn <- openConnection (optDbPath opts)
  -- Ensure the schema exists
  ensureSchema conn

  -- Read the log file content as Text
  logContent <- TIO.readFile (optLogFile opts)
  -- Split the content into lines
  let logLines = T.lines logContent

  -- Iterate over each line and attempt to parse it
  forM_ logLines $ \line -> do
    -- Skip empty lines
    if T.null line
      then return () -- Do nothing for empty lines
      else do
        -- Run the parser on the line
        let result = parse connectionEventParser "log line" line
        case result of
          Left bundle -> do
            -- Silently ignore parse errors for now
            return ()
          Right event -> do
            -- Only process 'Connected' events for now, creating initial sessions
            case eventType event of
              Connected -> do
                -- Convert ConnectionEvent to UserSession
                let session = userSessionFromConnectedEvent event
                -- Insert the session into the database
                insertSession conn session
                -- Optional: Print confirmation
                -- putStrLn $ "Inserted session: " ++ show session
              Disconnected -> do
                -- For now, just print a message. The pairing logic will come later.
                -- putStrLn $ "Skipped Disconnected event (pairing not yet implemented): " ++ show event
                return () -- Do nothing for Disconnected events in this commit

  -- Close the database connection after processing
  closeConnection conn
  putStrLn "Log parsing and database storage completed."

-- | Helper function to convert a 'ConnectionEvent' (Connected) into an initial 'UserSession'.
--   The 'disconnect_time' is set to 'Nothing'.
userSessionFromConnectedEvent :: ConnectionEvent -> UserSession
userSessionFromConnectedEvent event = UserSession
  { sessionId = -1 -- Placeholder ID, will be auto-generated by the database
  , sessionClientId = clientId $ eventClient event
  , sessionClientName = clientName $ eventClient event
  , sessionConnectTime = eventTimestamp event
  , sessionDisconnectTime = Nothing -- Initial value for a connected session
  }